login:
    path:     /login
    defaults: { _controller: UserUserBundle:Default:index }
signup:
    path:     /signup
    defaults: { _controller: UserUserBundle:Default:signup}
dashboard:
    path:    /dashboard
    defaults: { _controller: UserUserBundle:Default:dashboard}
checkuser:
    path:    /checkuser
    defaults: { _controller: UserUserBundle:User:checkUser}
    requirements:
saveuser:
    path:    /saveuser
    defaults: { _controller: UserUserBundle:User:saveUser}
    requirements:
logout:
    path:    /logout
    defaults: { _controller: UserUserBundle:User:logoutUser}
    requirements:
updateuser:
    path:    /updateuser
    defaults: { _controller: UserUserBundle:User:updateUser}
    requirements:
changepass:
    path:    /changepass
    defaults: { _controller: UserUserBundle:Default:changePass}
    requirements:
updatepass:
    path:    /updatepass
    defaults: {_controller: UserUserBundle:User:updatePass}
activate:
    path:    /activate
    defaults: {_controller: UserUserBundle:User:activateAccount}