login:
    path:     /login
    defaults: { _controller: UserUserBundle:Default:index }
signup:
    path:     /signup
    defaults: { _controller: UserUserBundle:Default:signup}
dashboard:
    path:    /dashboard
    defaults: { _controller: UserUserBundle:Default:dashboard}
checkuser:
    path:    /checkuser
    defaults: { _controller: UserUserBundle:User:checkUser}
    requirements:
saveuser:
    path:    /saveuser
    defaults: { _controller: UserUserBundle:User:saveUser}
    requirements:
logout2:
    path:    /logout2
    defaults: { _controller: UserUserBundle:User:logoutUser}
    requirements:
updateuser:
    path:    /updateuser
    defaults: { _controller: UserUserBundle:User:updateUser}
    requirements:
changepass:
    path:    /changepass
    defaults: { _controller: UserUserBundle:Default:changePass}
    requirements:
updatepass:
    path:    /updatepass
    defaults: {_controller: UserUserBundle:User:updatePass}
activate:
    path:    /activate
    defaults: {_controller: UserUserBundle:Default:activateAccount}
forgotpass:
    path:    /forgotpass
    defaults: {_controller: UserUserBundle:Default:forgotPass}
saveforgotpass:
    path:    /saveforgotpass
    defaults: {_controller: UserUserBundle:User:saveUserConfirmation}
test:
    path:    /test
    defaults: {_controller: UserUserBundle:Default:test}
resetpassword:
    path:    /resetpassword
    defaults: {_controller: UserUserBundle:Default:resetPass}
login_check:
    pattern: /login_check
logout:
    pattern: /logout