services:
#    user_user.example:
#        class: User\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     user.userbundle.mapper:
        class: User\UserBundle\Mapper\UserMapper
        arguments: [@doctrine.orm.entity_manager]
     sha256salted_encoder:
        class: User\UserBundle\Service\PasswordHash