security:
    encoders:
        User\UserBundle\Entity\User: sha512
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
 
    providers:
        user_db:
            entity: { class: User\UserBundle\Entity\User, property: email}
 
    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
                username_parameter: 'login[email]'
                password_parameter: 'login[password]'
                default_target_path: /dashboard
                failure_path: /login
            logout:
                path: /logout
                target: /login
            remember_me:
                key: MiPassphrase
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /dashboard, roles: ROLE_USER }
        - { path: /changepass, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }