User\UserBundle\Entity\User:
    type: entity
    table: userstat
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            scale: 10
        password:
            type: string
            scale: 100
        stat:
            type: integer
